---
title: "2023 Week 32: Hot Ones"
format: html
---

```{r setup}
library(ggtext)
library( showtext, warn.conflicts=F )
library( khroma  , warn.conflicts=F )
library(tidyverse)

# Based on https://github.com/z3tt/TidyTuesday/blob/main/R/2020_31_PalmerPenguins.Rmd
font_family <- 'Inter' # Alt: 'Lato', 'EB Garamond'; sysfonts::font.files() %>% pull(family) %>% unique()
if(nrow(sysfonts::font_files() %>% filter(family == font_family))){
	font_add( font_family
			  , regular    = paste0( font_family, '-Regular.otf'    )
			  , bold       = paste0( font_family, '-Bold.otf'       )
			  , italic     = paste0( font_family, '-Italic.otf'     )
			  , bolditalic = paste0( font_family, '-BoldItalic.otf' ) )
}else{
	font_add_google(font_family) #Note(Kim): Inter has no italic version
}
showtext_opts(dpi=300)
showtext_auto()

theme_set(theme_minimal( base_size = 10, base_family = font_family ))
theme_update( panel.grid.minor = element_blank()
			  ,  text = element_text(family=font_family)
			  ,  plot.title    = element_text( hjust=0, size=21, colour='black' , face='bold'       , margin=margin( t=0 , r=5, b=0, l=0 )                  )
			  ,  plot.subtitle = element_text( hjust=0, size=14, colour='grey60', face='bold.italic', margin=margin( t=0 , r=5, b=10, l=0 )                  )
			  ,  plot.caption  = element_text( hjust=1, size=10, colour='black' , face='plain'      , margin=margin( t=10, r=0, b=0 , l=0 ), lineheight=2.05 )
			  ,  plot.title.position   = 'plot'
			  ,  plot.caption.position = 'plot'
			  ,  axis.title = element_text(family=font_family)
			  ,  plot.margin = margin(rep( 10, 4 )) )
```

## Data Wrangling

```{r loading}
episodes <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-08-08/episodes.csv')
sauces   <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-08-08/sauces.csv')
seasons  <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-08-08/seasons.csv')
```

```{r}
min_date <- min(episodes$original_release)
max_date <- max(episodes$original_release)
df_well_known <- sauces %>% 
	filter(sauce_name %in% c( 'Sriracha', 'Tabasco' )) %>% 
	mutate( start_date=min_date, end_date=max_date )

sauces %>% 
	left_join( select( episodes, season, original_release ), by='season', relationship='many-to-many' ) %>% 
	ggplot() +
	geom_segment( data=df_well_known, mapping=aes( x=start_date, xend=end_date, y=scoville, yend=scoville ), colour='#EAECCC', linetype='dashed' ) +
	geom_line(aes( x=original_release, y=scoville, group=sauce_number, colour=sauce_number-5 )) +
	geom_text( data=df_well_known, mapping=aes( x=end_date, y=scoville, label=sauce_name ), colour='#EAECCC', inherit.aes=F, hjust=0 ) +
	coord_cartesian( clip='off', xlim=c( min_date, max_date ) ) +
	scale_y_continuous( trans='log10', labels=scales::comma ) +
	scale_colour_sunset() +
	theme(legend.position='none') +
	ylab('') +
	xlab('Air Date') +
	labs( title='Hot Ones Hot Sauce Gauntlet in Scolville' ) +
	theme(plot.margin=margin(r=25) ) +
	theme( plot.background = element_rect(fill='#444444')
	     , panel.grid.major = element_line( colour='#555555', linewidth=rel(0.5) )
	     , axis.title    = element_text(colour='#EAECCC')
	     , plot.title    = element_text(colour='#EAECCC')
	     , plot.subtitle = element_text(colour='#AAAAAA')
	     , plot.caption  = element_text(colour='#AAAAAA')
	     , axis.text     = element_text(colour='#EAECCC') )

ggsave( '2023_wk32.png', width=16/2, height=10/2 )
```

