name: tidy_tuesday
channels:
  - conda-forge
dependencies:
# Base R
  - r
  - r-devtools
  - r-tidyverse
  - r-inspectdf
# Plotting
  - r-ggally
  - r-ggdist
  - r-ggforce
  - r-ggbreak
  - r-ggbump
  - r-ggtext
  - r-ggrepel
  - r-ggthemes
  - r-patchwork
  - r-showtext
  - r-svglite
  - r-ggblend
  - r-ggbump
  - r-ggspatial
  - r-ggpointdensity
  - r-shape
  - r-gganimate=1.0.7 #Version that work with gganimate with specified transformr version
  - r-gifski
# Maps
  - r-maps
  - r-sf
  - r-terra
  - r-ncdf4
  - r-rnaturalearth
  - r-geosphere
  - r-lwgeom
  - r-transformr=0.1.3 #Version that work with gganimate with specified gganimate version
