name: tidy_tuesday
channels:
  - conda-forge
dependencies:
  - r
  - r-tidyverse
  - r-ggally
  - r-ggdist
  - r-ggforce
  - r-ggbreak
  - r-ggtext
  - r-ggrepel
  - r-ggthemes
  - r-patchwork
  - r-maps
  - r-sf
  - r-ggpointdensity
  - r-tidygeocoder
  - r-shape
  - r-showtext
  - r-svglite
