# 2022 May 10th

## Data Wrangling
```{r}
#nyt_titles <- read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-05-10/nyt_titles.tsv')

nyt_full <- read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-05-10/nyt_full.tsv')

df <- nyt_full %>%
	group_by(title_id) %>% 
	mutate(weeks_post_debut=as.integer(difftime(week, min(week), units='weeks')))%>% 
	ungroup() %>% 
	mutate(author_id=match(author,unique(author))
		  , title_id=title_id+1)

df_per_book <- df %>%
	group_by(author_id,title_id) %>% 
	summarise( weeks_total=n()
			 , week_span=max(weeks_post_debut)
			 , max_rank=min(rank)
			 , debut_rank=head(rank, 1)) %>% 
	ungroup() %>% 
	subset(complete.cases(.))
	
```

## EDA
```{r}
df %>% ggplot(aes(x=log1p(weeks_post_debut))) +
	geom_bar(stat='bin') +
	scale_colour_tableau()

df_per_book %>% ggplot(aes(x=max_rank)) +
	geom_bar() +
	scale_colour_tableau()
```

## Basic Model

\begin{tikzcd}
& A \arrow[dl] \arrow[dr] \\
D \arrow[rr] && MR
\end{tikzcd}

```{r}
dat = list( MR=df_per_book$max_rank
          , D =df_per_book$debut_rank 
		  , A =df_per_book$author_id
		  , a =rep(2,max(df_per_book$max_rank)-1) )

m1 <- alist( MR ~ dordlogit( phi, alpha )
			  , phi <- bD * sum( delta_d[1:D] )
			  , bD    ~ dnorm(0,1)
			  , alpha ~ dnorm(0,1) 
			  , vector[17]: delta_d <<- append_row(0, delta)
			  , simplex[16]: delta ~ dirichlet(a) )

m2<- alist( MR ~ dordlogit( phi, alpha )
			  , phi <- bD * sum( delta_d[1:D] ) + bA_bar + zA[A]*sigma
			  , bD    ~ dnorm(0,0.5)
			  , alpha ~ dnorm(0,1) 
			  , zA[A] ~ dnorm( 0, 1 )
			  , bA_bar ~ dnorm( 0, 1.5 )
		      , sigma ~ dexp(1)
			  , vector[17]: delta_d <<- append_row(0, delta)
			  , simplex[16]: delta ~ dirichlet(a) 
			  , gq> vector[A]:bA <<- bA_bar + zA[A]*sigma)

hmc1 <- ulam(m1, data=dat, chains=4, cores=8, threads=2, log_lik=TRUE )
hmc1 <- ulam(m2, data=dat, chains=4, cores=8, threads=2, log_lik=TRUE )
```

